name: pydda-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - arm_pyart
  - pip
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - pytest
  - pytest-mpl
  - pytest-cov
  - cartopy
  - cfgrib
  - eccodes
  - dask
  - distributed
  - sphinx
  - numpydoc
  - tensorflow>=2.6
  - tensorflow-probability
  - pip:
    - sphinx_gallery
