name: pydda-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - arm_pyart
  - pytest
  - pytest-mpl
  - pytest-cov
  - cartopy
  - cfgrib
  - eccodes
  - sphinx
  - tensorflow
  - tensorflow-probability
  - herbie-data
  - pip:
    - sphinx_gallery
    - sphinx-copybutton
    - pydata-sphinx-theme<0.9.0
    - sphinx_design
