name: pydda-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - arm_pyart
  - cython
  - cmweather
  - pytest
  - pytest-mpl
  - pytest-cov
  - cartopy
  - pyproj=3.3
  - cfgrib
  - eccodes
  - sphinx
  - tensorflow
  - tensorflow-probability
  - herbie-data
  - nbsphinx
  - pydata-sphinx-theme
  - pooch
  - cmweather
  - myst-nb
  - sphinx-gallery
  - sphinx-copybutton
  - sphinx-design
