name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - pytest
  - pytest-mpl
  - pytest-cov
  - cartopy
  - cfgrib
  - eccodes
  - dask
  - distributed
  - pip:
     - arm_pyart
